import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/ui/header";
import { mulish } from "@/components/ui/fonts";
import Footer from "@/components/ui/footer";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mulish.className} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
        <Toaster />
      </body>
    </html>
  );
}
